// <auto-generated />
using System;
using System.Collections.Generic;
using B2X.Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2X.Catalog.src.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_CatalogImport_TenantId");

                    b.HasIndex("TenantId", "SupplierId", "CatalogId", "ImportTimestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogImport_CompositeKey");

                    b.ToTable("CatalogImports");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierAid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogImportId")
                        .HasDatabaseName("IX_CatalogProduct_CatalogImportId");

                    b.HasIndex("CatalogImportId", "SupplierAid")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogProduct_ImportId_SupplierAid");

                    b.ToTable("CatalogProducts");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogShareRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOverride")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApplyToAggregations")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CatalogShareId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ExcludedBrandIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("ExcludedCategorySlugsJson")
                        .HasColumnType("text");

                    b.Property<string>("ExcludedProductIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("IncludedBrandIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("IncludedCategorySlugsJson")
                        .HasColumnType("text");

                    b.Property<string>("IncludedProductIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogShareId")
                        .HasDatabaseName("IX_CatalogShareRule_CatalogShareId");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_CatalogShareRule_Target");

                    b.ToTable("CatalogShareRules");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ReducedVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("StandardVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TaxRate_CountryCode");

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bb3c3a4-a770-44e4-a67f-47215d2fb23f"),
                            CountryCode = "AT",
                            CountryName = "Austria",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3600),
                            ReducedVatRate = 10m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("4d31726b-af8e-4c8d-8cdb-41b9d8875f72"),
                            CountryCode = "BE",
                            CountryName = "Belgium",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3817),
                            ReducedVatRate = 6m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("b479a08b-663e-42f3-82cc-94d48293a702"),
                            CountryCode = "BG",
                            CountryName = "Bulgaria",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3819),
                            ReducedVatRate = 9m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("02936643-30b5-4539-9e45-6d63d25babfc"),
                            CountryCode = "HR",
                            CountryName = "Croatia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3821),
                            ReducedVatRate = 13m,
                            StandardVatRate = 25m
                        },
                        new
                        {
                            Id = new Guid("b82f0e11-c388-4f7e-86cd-1ec743f767f4"),
                            CountryCode = "CY",
                            CountryName = "Cyprus",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3830),
                            ReducedVatRate = 9m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("aa0badc9-ec43-4a2a-893f-ace50090126f"),
                            CountryCode = "CZ",
                            CountryName = "Czech Republic",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3843),
                            ReducedVatRate = 15m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("cc159c01-21a3-4513-b799-1128fd879780"),
                            CountryCode = "DK",
                            CountryName = "Denmark",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3847),
                            ReducedVatRate = 0m,
                            StandardVatRate = 25m
                        },
                        new
                        {
                            Id = new Guid("8d8a0b4b-e297-4611-8747-2328e04c3f4d"),
                            CountryCode = "EE",
                            CountryName = "Estonia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3848),
                            ReducedVatRate = 9m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("b877f898-83b2-4d75-84bc-597f7d7333a3"),
                            CountryCode = "FI",
                            CountryName = "Finland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3850),
                            ReducedVatRate = 14m,
                            StandardVatRate = 24m
                        },
                        new
                        {
                            Id = new Guid("00ac79c0-23c8-4521-a120-f99788644961"),
                            CountryCode = "FR",
                            CountryName = "France",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3873),
                            ReducedVatRate = 5.5m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("6047c81c-8037-45fd-934e-0857f2211bfa"),
                            CountryCode = "DE",
                            CountryName = "Germany",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3875),
                            ReducedVatRate = 7m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("7223b111-6d43-4e9f-82b8-ebd5aac92910"),
                            CountryCode = "GR",
                            CountryName = "Greece",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3876),
                            ReducedVatRate = 13m,
                            StandardVatRate = 24m
                        },
                        new
                        {
                            Id = new Guid("a1e971dc-462e-42ea-b610-cf78fe51d1fd"),
                            CountryCode = "HU",
                            CountryName = "Hungary",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3879),
                            ReducedVatRate = 18m,
                            StandardVatRate = 27m
                        },
                        new
                        {
                            Id = new Guid("260e5b59-5fd3-45dc-a008-abd9cafd513e"),
                            CountryCode = "IE",
                            CountryName = "Ireland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3881),
                            ReducedVatRate = 13.5m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("869cb317-4f1a-483d-ae9d-14072a304c0f"),
                            CountryCode = "IT",
                            CountryName = "Italy",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3892),
                            ReducedVatRate = 10m,
                            StandardVatRate = 22m
                        },
                        new
                        {
                            Id = new Guid("57a3749c-9e1c-43b1-b31c-2bbe5ea7d5b0"),
                            CountryCode = "LV",
                            CountryName = "Latvia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3894),
                            ReducedVatRate = 12m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("33db00b1-97df-4021-b2c6-9f734c8f04b3"),
                            CountryCode = "LT",
                            CountryName = "Lithuania",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3896),
                            ReducedVatRate = 9m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("42da6a0f-80a7-4e4e-a585-e897a850359d"),
                            CountryCode = "LU",
                            CountryName = "Luxembourg",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3897),
                            ReducedVatRate = 8m,
                            StandardVatRate = 17m
                        },
                        new
                        {
                            Id = new Guid("80a8fd57-dcdc-41d8-9c67-b0d418e5b790"),
                            CountryCode = "MT",
                            CountryName = "Malta",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3899),
                            ReducedVatRate = 7m,
                            StandardVatRate = 18m
                        },
                        new
                        {
                            Id = new Guid("b52bd8d8-7151-4dc6-b774-fb988572434c"),
                            CountryCode = "NL",
                            CountryName = "Netherlands",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3900),
                            ReducedVatRate = 9m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("bd29fe8c-4e58-4eb5-b892-88a7e75a46c7"),
                            CountryCode = "PL",
                            CountryName = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3903),
                            ReducedVatRate = 8m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("6fa777eb-3841-4611-a1be-a21aad16001e"),
                            CountryCode = "PT",
                            CountryName = "Portugal",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3904),
                            ReducedVatRate = 13m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("e97607b0-63cd-456a-9c4f-db24052a0e19"),
                            CountryCode = "RO",
                            CountryName = "Romania",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3906),
                            ReducedVatRate = 9m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("576a203d-755b-43e2-ab1d-a2ae41f8ae7e"),
                            CountryCode = "SK",
                            CountryName = "Slovakia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3907),
                            ReducedVatRate = 10m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("f0293508-b564-4459-b1e1-8df645df0a84"),
                            CountryCode = "SI",
                            CountryName = "Slovenia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3908),
                            ReducedVatRate = 9.5m,
                            StandardVatRate = 22m
                        },
                        new
                        {
                            Id = new Guid("76f8bcc9-181b-49cd-8646-338602f828ef"),
                            CountryCode = "ES",
                            CountryName = "Spain",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3910),
                            ReducedVatRate = 10m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("0cf4be29-3179-471c-947b-6ecfe536db65"),
                            CountryCode = "SE",
                            CountryName = "Sweden",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 11, 22, 52, 42, 99, DateTimeKind.Utc).AddTicks(3911),
                            ReducedVatRate = 12m,
                            StandardVatRate = 25m
                        });
                });

            modelBuilder.Entity("B2X.Catalog.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Categories_ParentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Categories_TenantId");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_TenantId_Slug");

                    b.HasIndex("TenantId", "IsActive", "IsVisible")
                        .HasDatabaseName("IX_Categories_TenantId_Active_Visible");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("B2X.Catalog.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Products_CreatedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Products_TenantId");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_Products_TenantId_IsActive");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_TenantId_Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("B2X.Catalog.Models.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBackorders")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, string>>("Attributes")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Variants_ProductId");

                    b.HasIndex("ProductId", "IsActive")
                        .HasDatabaseName("IX_Variants_ProductId_IsActive");

                    b.HasIndex("ProductId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Variants_ProductId_Sku");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId")
                        .HasName("PK_ProductCategories");

                    b.HasIndex(new[] { "CategoryId" }, "IX_ProductCategories_CategoryId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductCategories_ProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogProduct", b =>
                {
                    b.HasOne("B2X.Catalog.Core.Entities.CatalogImport", "CatalogImport")
                        .WithMany("Products")
                        .HasForeignKey("CatalogImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogImport");
                });

            modelBuilder.Entity("B2X.Catalog.Models.Category", b =>
                {
                    b.HasOne("B2X.Catalog.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("B2X.Catalog.Models.Variant", b =>
                {
                    b.HasOne("B2X.Catalog.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("B2X.Catalog.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductCategories_Categories_CategoryId");

                    b.HasOne("B2X.Catalog.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductCategories_Products_ProductId");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogImport", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("B2X.Catalog.Models.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
