// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using B2X.LayoutService.Data;

#nullable disable

namespace B2X.LayoutService.Migrations
{
    [DbContext(typeof(LayoutDbContext))]
    [Migration("20251225000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2X.LayoutService.Models.CmsComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<string>("DataBinding")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Styling")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Variables")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SectionId")
                        .HasName("IX_Components_SectionId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("B2X.LayoutService.Models.CmsPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledPublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasName("IX_Pages_TenantId");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasName("IX_Pages_TenantId_Slug");

                    b.HasIndex("TenantId", "Visibility")
                        .HasName("IX_Pages_TenantId_Visibility");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("B2X.LayoutService.Models.CmsSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Layout")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<string>("Styling")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PageId")
                        .HasName("IX_Sections_PageId");

                    b.HasOne("B2X.LayoutService.Models.CmsPage")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("B2X.LayoutService.Models.ComponentDefinition", b =>
                {
                    b.Property<string>("ComponentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("PresetVariants")
                        .HasColumnType("jsonb");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<string>("Slots")
                        .HasColumnType("jsonb");

                    b.HasKey("ComponentType");

                    b.ToTable("ComponentDefinitions");

                    b.HasData(
                        new
                        {
                            ComponentType = "Button",
                            Category = "Interactive",
                            Description = "A clickable button component",
                            DisplayName = "Button",
                            Icon = "button"
                        },
                        new
                        {
                            ComponentType = "TextBlock",
                            Category = "Content",
                            Description = "A text content block",
                            DisplayName = "Text Block",
                            Icon = "text"
                        },
                        new
                        {
                            ComponentType = "Image",
                            Category = "Media",
                            Description = "An image component",
                            DisplayName = "Image",
                            Icon = "image"
                        },
                        new
                        {
                            ComponentType = "Form",
                            Category = "Interactive",
                            Description = "A form component",
                            DisplayName = "Form",
                            Icon = "form"
                        },
                        new
                        {
                            ComponentType = "Card",
                            Category = "Container",
                            Description = "A card container component",
                            DisplayName = "Card",
                            Icon = "card"
                        });
                });

            modelBuilder.Entity("B2X.LayoutService.Models.CmsComponent", b =>
                {
                    b.HasOne("B2X.LayoutService.Models.CmsSection", null)
                        .WithMany("Components")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("B2X.LayoutService.Models.CmsSection", b =>
                {
                    b.HasOne("B2X.LayoutService.Models.CmsPage", null)
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
