// <auto-generated />
using System;
using B2Connect.CMS.Core.Domain.Pages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2Connect.CMS.Infrastructure.Migrations
{
    [DbContext(typeof(B2Connect.CMS.Infrastructure.Repositories.CmsDbContext))]
    partial class CmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2Connect.CMS.Core.Domain.Pages.TemplateOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("PageDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("page_definition");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_template_overrides");

                    b.ToTable("template_overrides", (string)null);
                });

            modelBuilder.Entity("B2Connect.CMS.Core.Domain.Pages.TemplateOverrideMetadata", b =>
                {
                    b.Property<Guid>("OverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_id");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_validated");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("validation_status");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_results");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("OverrideId")
                        .HasName("pk_template_override_metadata");

                    b.ToTable("template_override_metadata", (string)null);
                });

            modelBuilder.Entity("B2Connect.CMS.Core.Domain.Pages.TemplateOverrideMetadata", b =>
                {
                    b.HasOne("B2Connect.CMS.Core.Domain.Pages.TemplateOverride", null)
                        .WithOne("OverrideMetadata")
                        .HasForeignKey("B2Connect.CMS.Core.Domain.Pages.TemplateOverrideMetadata", "OverrideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_override_metadata_template_overrides_override_id");
                });
#pragma warning restore 612, 618
        }
    }
}