// <auto-generated />
using System;
using B2X.Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2X.Catalog.src.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_CatalogImport_TenantId");

                    b.HasIndex("TenantId", "SupplierId", "CatalogId", "ImportTimestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogImport_CompositeKey");

                    b.ToTable("CatalogImports");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProductData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierAid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogImportId")
                        .HasDatabaseName("IX_CatalogProduct_CatalogImportId");

                    b.HasIndex("CatalogImportId", "SupplierAid")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogProduct_ImportId_SupplierAid");

                    b.ToTable("CatalogProducts");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ReducedVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("StandardVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TaxRate_CountryCode");

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67da7019-375d-4f90-9d98-201c82e69668"),
                            CountryCode = "AT",
                            CountryName = "Austria",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1680),
                            ReducedVatRate = 10m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("eb2d8c4f-a80f-4d67-80e8-e0857e76a970"),
                            CountryCode = "BE",
                            CountryName = "Belgium",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1890),
                            ReducedVatRate = 6m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("7b716df7-178a-4efb-b436-fde1fa2f3e0d"),
                            CountryCode = "BG",
                            CountryName = "Bulgaria",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1890),
                            ReducedVatRate = 9m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("f0cdc4d5-bd8a-4c3e-a648-47ee70f451ac"),
                            CountryCode = "HR",
                            CountryName = "Croatia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1890),
                            ReducedVatRate = 13m,
                            StandardVatRate = 25m
                        },
                        new
                        {
                            Id = new Guid("c23f9032-60bc-45b4-9057-d295efcb8085"),
                            CountryCode = "CY",
                            CountryName = "Cyprus",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1900),
                            ReducedVatRate = 9m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("cf024566-e1e2-4ec4-ada3-aeb8d4280625"),
                            CountryCode = "CZ",
                            CountryName = "Czech Republic",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1900),
                            ReducedVatRate = 15m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("6025a514-069d-4648-b3cb-6dbcaa9899ed"),
                            CountryCode = "DK",
                            CountryName = "Denmark",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1910),
                            ReducedVatRate = 0m,
                            StandardVatRate = 25m
                        },
                        new
                        {
                            Id = new Guid("28697dc0-079e-4726-9c90-538f387b8239"),
                            CountryCode = "EE",
                            CountryName = "Estonia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1910),
                            ReducedVatRate = 9m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("4d6a2f85-bb50-474d-bbf0-aa0332356c48"),
                            CountryCode = "FI",
                            CountryName = "Finland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1910),
                            ReducedVatRate = 14m,
                            StandardVatRate = 24m
                        },
                        new
                        {
                            Id = new Guid("8798f28a-7b43-42c3-a708-68b592c84455"),
                            CountryCode = "FR",
                            CountryName = "France",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1930),
                            ReducedVatRate = 5.5m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("2a9167e2-ff70-44b8-bd42-bdd78f589c44"),
                            CountryCode = "DE",
                            CountryName = "Germany",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1930),
                            ReducedVatRate = 7m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("c1df6f92-fb89-4d6b-8ce9-b882adfcfc1f"),
                            CountryCode = "GR",
                            CountryName = "Greece",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1940),
                            ReducedVatRate = 13m,
                            StandardVatRate = 24m
                        },
                        new
                        {
                            Id = new Guid("644da01e-5156-4f0d-af50-38ec4f31e4b8"),
                            CountryCode = "HU",
                            CountryName = "Hungary",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1940),
                            ReducedVatRate = 18m,
                            StandardVatRate = 27m
                        },
                        new
                        {
                            Id = new Guid("5727d992-5a6d-4606-ba67-7ed21a318e80"),
                            CountryCode = "IE",
                            CountryName = "Ireland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1950),
                            ReducedVatRate = 13.5m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("11440f7d-5bd9-48cf-af40-35d110b7ffee"),
                            CountryCode = "IT",
                            CountryName = "Italy",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1950),
                            ReducedVatRate = 10m,
                            StandardVatRate = 22m
                        },
                        new
                        {
                            Id = new Guid("1be26f51-fbbd-4ba5-a5b8-01e574a5b1a9"),
                            CountryCode = "LV",
                            CountryName = "Latvia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1950),
                            ReducedVatRate = 12m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("152dbbe7-3a52-49a0-992c-8c8d446c66f9"),
                            CountryCode = "LT",
                            CountryName = "Lithuania",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1960),
                            ReducedVatRate = 9m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("191d66e6-40de-4bd1-801d-a349e0a0ab11"),
                            CountryCode = "LU",
                            CountryName = "Luxembourg",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1960),
                            ReducedVatRate = 8m,
                            StandardVatRate = 17m
                        },
                        new
                        {
                            Id = new Guid("5eef59f3-fae0-4acf-9a4a-69069aa78b51"),
                            CountryCode = "MT",
                            CountryName = "Malta",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1960),
                            ReducedVatRate = 7m,
                            StandardVatRate = 18m
                        },
                        new
                        {
                            Id = new Guid("9da79400-087b-435a-add3-ee3107c56e66"),
                            CountryCode = "NL",
                            CountryName = "Netherlands",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1970),
                            ReducedVatRate = 9m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("92119491-36dd-4612-8197-4cee3a1d940d"),
                            CountryCode = "PL",
                            CountryName = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1970),
                            ReducedVatRate = 8m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("fc330729-33b3-486f-8f5f-3b95cacacf6e"),
                            CountryCode = "PT",
                            CountryName = "Portugal",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1980),
                            ReducedVatRate = 13m,
                            StandardVatRate = 23m
                        },
                        new
                        {
                            Id = new Guid("b1c00c89-2180-47ae-bb1d-1c3182a86472"),
                            CountryCode = "RO",
                            CountryName = "Romania",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1980),
                            ReducedVatRate = 9m,
                            StandardVatRate = 19m
                        },
                        new
                        {
                            Id = new Guid("68c539df-be8e-4cee-b2a0-faa5cd92fa66"),
                            CountryCode = "SK",
                            CountryName = "Slovakia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1980),
                            ReducedVatRate = 10m,
                            StandardVatRate = 20m
                        },
                        new
                        {
                            Id = new Guid("be55eeae-0cc9-432c-8333-91b726cb6579"),
                            CountryCode = "SI",
                            CountryName = "Slovenia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1990),
                            ReducedVatRate = 9.5m,
                            StandardVatRate = 22m
                        },
                        new
                        {
                            Id = new Guid("c1d1e06d-7374-460b-b343-4eeeaa06e2ae"),
                            CountryCode = "ES",
                            CountryName = "Spain",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1990),
                            ReducedVatRate = 10m,
                            StandardVatRate = 21m
                        },
                        new
                        {
                            Id = new Guid("ba2ea061-8986-46ec-b3e1-362bb5a51a73"),
                            CountryCode = "SE",
                            CountryName = "Sweden",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2026, 1, 3, 9, 21, 19, 39, DateTimeKind.Utc).AddTicks(1990),
                            ReducedVatRate = 12m,
                            StandardVatRate = 25m
                        });
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogProduct", b =>
                {
                    b.HasOne("B2X.Catalog.Core.Entities.CatalogImport", "CatalogImport")
                        .WithMany("Products")
                        .HasForeignKey("CatalogImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogImport");
                });

            modelBuilder.Entity("B2X.Catalog.Core.Entities.CatalogImport", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
